### ISSUE TITLE
工程无法打开

### ISSUE THREAD

**Issue by COCORONGZHENG** [RockChanel/SWForm#2]
打开就报错，你这也没有使用pod吧，请楼主download一个试一下

**Comment by RockChanel** [comment]
@COCORONGZHENG  是报这个错么 incompatible project version

**Comment by COCORONGZHENG** [comment]
是的

**Comment by RockChanel** [comment]
@COCORONGZHENG readme 里面写了解决方法

Warning

若下载项目之后，运行报错 incompatible project version，是由于此项目创建 Xcode 版本为 9.4.1。若运行 Xcode 版本低于此版本，解决方法如下：

方法一：更新 Xcode 版本

方法二：右键 SWFormExample.xcodeproj， 点击显示包内容，打开 project.pbxproj 文件，修改降低 objectVersion 即可运行

**Comment by wangppppp** [comment]
界面无法释放啊
